name: my_bjp
description: MY BJP ASSAM

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  esys_flutter_share: ^1.0.2
  readmore: ^1.0.1
  pull_to_refresh: ^1.6.4
  firebase_core: ^1.0.0
  firebase_messaging: ^9.0.0
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^6.0.2
  google_fonts: any
  auto_size_text: ^2.1.0
  #path_provider: ^2.0.0

  video_player: ^2.0.0
  auto_orientation: ^1.0.6
  chewie: ^1.0.0

  cached_network_image: any

  fluttertoast: ^7.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/images/line.png
    - lib/images/20degree_256.gif
    - lib/images/bjp_app_logo_whole_round_AS.png
    - lib/images/flower_leading.png
    - lib/images/only_text_AS.png
    - lib/images/bjp_logo_black.png
    - lib/assets/
