name: my_bjp
description: MY BJP ASSAM

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  path_provider: ^1.6.27
  permission_handler: ^5.0.1+1
  #share: ^0.6.5+4
  esys_flutter_share: ^1.0.2
  readmore: ^1.0.0
  transparent_image: ^1.0.0
  pull_to_refresh: 1.6.3
  pdf_flutter: ^1.1.3
  #webview_flutter: ^1.0.7
  connectivity: ^2.0.2
  provider: ^4.3.3
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_messaging: ^5.1.6
  flutter_local_notifications: ^3.0.3
  rxdart: ^0.25.0
  flutter_webview_plugin: ^0.3.11
  flutter_downloader: ^1.5.2
  url_launcher: ^5.7.10
  google_fonts: ^1.1.2
  auto_size_text: ^2.1.0

  #flutter_inappwebview: ^4.0.0+4
  #flutter_webview_plugin: ^0.3.11
  #flutter_webview_plugin:
  #  git: https://github.com/nuc134r/flutter_webview_plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_native_splash: ^0.2.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/line.png
    - lib/images/20degree_256.gif
    - lib/images/bjp_app_logo_whole_round_AS.png
    - lib/images/flower_leading.png
    - lib/images/only_text_AS.png
    - lib/images/bjp_logo_black.png
    #- lib/texts/antyodaya.txt
    #- lib/texts/history_development.txt
    #- lib/texts/integral_humanism.txt
    #- lib/texts/philosophy.txt
    - lib/assets/
  # An image asset can refer to one or more resolution-specific "svariants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
